name: pak test 
on: [push]
jobs:
  R-CMD-check:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
    steps:

    - name: setup pandoc
      uses: r-lib/actions/setup-pandoc@v2

    - name: setup R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: release
        use-public-rspm: true

    - name: install dependencies
      uses: r-lib/actions/setup-r-dependencies@v2
      